connections:
  turing_emea_dev:
    account: sanofi-emea_comm
    database: GENMED_OMNI_DEV
    role: GENMED_OMNI_DEV_KEY_DEVELOPER
    warehouse: GENMED_OMNI_DEV_WH_ADHOC
  turing_emea_prod:
    account: sanofi-emea_comm
    database: GENMED_OMNI_PROD
    role: GENMED_OMNI_PROD_KEY_DEVELOPER
    warehouse: GENMED_OMNI_PROD_WH_ADHOC
  turing_emea_uat:
    account: sanofi-emea_comm
    database: GENMED_OMNI_UAT
    role: GENMED_OMNI_UAT_KEY_DEVELOPER
    warehouse: GENMED_OMNI_UAT_WH_ADHOC
  turing_amer_dev:
    account: sanofi-amer_comm
    database: GENMED_OMNI_AMER_DEV
    role: GENMED_OMNI_AMER_DEV_KEY_DEVELOPER
    warehouse: GENMED_OMNI_AMER_DEV_WH_ADHOC
  turing_amer_prod:
    account: sanofi-amer_comm
    database: GENMED_OMNI_AMER_PROD
    role: GENMED_OMNI_AMER_PROD_KEY_DEVELOPER
    warehouse: GENMED_OMNI_AMER_PROD_WH_ADHOC
  luci_emea_prod:
    account: sanofi-emea_df_ci
    database: DF_CI_PROD
    role: DF_CI_PROD_DEVELOPER
    warehouse: DF_CI_PROD_WH_ADHOC
  
  
login: charles.girard@sanofi.com
