select SALES.COUNTRY, SALES_DT, SALES.BRAND_ID, LOCAL_BRAND_NAME, GLOBAL_BRAND_NAME, sum(QUANTITY_SOLD), sum(SALES_AMOUNT), sum(UNITS_SOLD), sum(RX_COUNT), sum(RX_NUM)
from GENMED_OMNI_PROD.DWH_TURING.DWH_EXTERNAL_SALES_PERF as SALES
left join GENMED_OMNI_PROD.DWH_TURING.DWH_BRAND as BRAND
on BRAND.BRAND_ID = SALES.BRAND_ID
where SALES.COUNTRY = '%COUNTRY%' and BRAND.LOCAL_BRAND_NAME ilike '%BRAND%'
group by all